/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { proxy, useProxy } from "valtio";

const state = proxy({
  current: null,
  items: {
    roof: "#ffffff",
    wall: "blue",
  },
});


export default function Model({ props }) {
  const group = useRef();
  const snap = useProxy(state);
  const { nodes, materials } = useGLTF("/farmthreejs.glb");
  return (
    <group
      rotation={[0, Math.PI, 0]}
      position={[-5, -5, 0]}
      ref={group}
      {...props}
      dispose={null}
    >
      {/* FARM START */}
      <group
        position={[0, 1, 0]}>
        <mesh
          material-color={snap.items.wall}
          material={materials["Red Farm"]}
          geometry={nodes.Cube_1.geometry}
        />
        <mesh
          material-color={snap.items.roof}
          material={materials.Roof}
          geometry={nodes.Cube_2.geometry}
        />
        <mesh
          material={materials["White Paint"]}
          geometry={nodes.Cube_3.geometry}
        />
      </group>
      {/* FARM END */}
      <group position={[-0.42, 0.52, -0.41]}>
        <mesh
          material={materials["Red Farm"]}
          geometry={nodes.Cylindre_1.geometry}
        />
        <mesh material={materials.Roof} geometry={nodes.Cylindre_2.geometry} />
        <mesh
          material={materials["White Paint"]}
          geometry={nodes.Cylindre_3.geometry}
        />
      </group>
      <mesh
        material={materials.Grass}
        geometry={nodes.Plan.geometry}
        scale={[100, 100, 100]}
      />
      <group position={[2.94, 0.52, -0.41]}>
        <mesh
          material={materials["Red Farm"]}
          geometry={nodes.Cylindre001_1.geometry}
        />
        <mesh
          material={materials.Roof}
          geometry={nodes.Cylindre001_2.geometry}
        />
        <mesh
          material={materials["White Paint"]}
          geometry={nodes.Cylindre001_3.geometry}
        />
      </group>
      <group position={[6.38, 0.52, -0.41]}>
        <mesh
          material={materials["Red Farm"]}
          geometry={nodes.Cylindre002_1.geometry}
        />
        <mesh
          material={materials.Roof}
          geometry={nodes.Cylindre002_2.geometry}
        />
        <mesh
          material={materials["White Paint"]}
          geometry={nodes.Cylindre002_3.geometry}
        />
      </group>
      <mesh
        material={materials.BLÉ}
        geometry={nodes.Plan002.geometry}
        position={[9.67, 0.05, 0]}
        scale={[5.22, 5.22, 5.22]}
      />
      <mesh
        material={materials.BALLOT}
        geometry={nodes.Cube.geometry}
        position={[10.97, 0.17, 0]}
        scale={[0.17, 0.17, 0.17]}
      />
      <mesh
        material={materials.BALLOT}
        geometry={nodes.Cube001.geometry}
        position={[9.05, 0.17, 0]}
        scale={[0.17, 0.17, 0.17]}
      />
      <mesh
        material={materials.BALLOT}
        geometry={nodes.Cube002.geometry}
        position={[9.05, 0.17, -2.33]}
        scale={[0.17, 0.17, 0.17]}
      />
      <mesh
        material={materials.BALLOT}
        geometry={nodes.Cube003.geometry}
        position={[10.34, 0.17, -2.33]}
        scale={[0.17, 0.17, 0.17]}
      />
      <mesh
        material={materials.BALLOT}
        geometry={nodes.Cube004.geometry}
        position={[10.34, 0.17, 1.58]}
        scale={[0.17, 0.17, 0.17]}
      />
      <mesh
        material={materials.BALLOT}
        geometry={nodes.Cube005.geometry}
        position={[6.71, 0.17, 1.58]}
        scale={[0.17, 0.17, 0.17]}
      />
      <mesh
        material={materials.BALLOT}
        geometry={nodes.Cube006.geometry}
        position={[6.71, 0.17, -4.06]}
        scale={[0.17, 0.17, 0.17]}
      />
      <mesh
        material={materials.BALLOT}
        geometry={nodes.Cube007.geometry}
        position={[13.73, 0.17, -4.06]}
        scale={[0.17, 0.17, 0.17]}
      />
      <mesh
        material={materials.BALLOT}
        geometry={nodes.Cube008.geometry}
        position={[13.73, 0.17, 0.57]}
        scale={[0.17, 0.17, 0.17]}
      />
    </group>
  );
}

useGLTF.preload("/farmthreejs.glb");
